# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c53b678578558a2e0f0d4b3c1ee232b5c413605386edef53909f9360b2d9741d8d670f0dd00b7564b285ebd5c054f2ffb5ce06eec1dca7ba2aef84b64a30545

test:
  secret_key_base: 343660a558aa1628d5c55c52da92484e5ebfd0b820cab06e5d6cc2dd78aab43898503da736878e9b8b3eb02c34f1a947599f14840b0444bb861ba81abd437af7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: c90c199649493ed84f2e6b2c55c275f3b9a2cae43e86498475698c46ef27df059bf0469984fcaab27a1b7fe1d42755e293de9246470e3b2c9ac92583de1c08b9
